FROM postgres:latest

# Copie les certificats dans le conteneur
# À chaque --build (docker compose up --build) les fichiers seront copiés
COPY ../docker/certs/server.crt /etc/ssl/server.crt
COPY ../docker/certs/server.key /etc/ssl/server.key

# Fixe les permissions strictes requises
# À chaque --build (docker compose up --build) RUN sera exécuté
RUN chown postgres:postgres /etc/ssl/server.key && chmod 600 /etc/ssl/server.key
