--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assertion; Type: TABLE; Schema: public; Owner: delvauxo
--

CREATE TABLE public.assertion (
    store text NOT NULL,
    authorization_model_id text NOT NULL,
    assertions bytea
);


ALTER TABLE public.assertion OWNER TO delvauxo;

--
-- Name: authorization_model; Type: TABLE; Schema: public; Owner: delvauxo
--

CREATE TABLE public.authorization_model (
    store text NOT NULL,
    authorization_model_id text NOT NULL,
    type text NOT NULL,
    type_definition bytea,
    schema_version text DEFAULT '1.0'::text NOT NULL,
    serialized_protobuf bytea
);


ALTER TABLE public.authorization_model OWNER TO delvauxo;

--
-- Name: changelog; Type: TABLE; Schema: public; Owner: delvauxo
--

CREATE TABLE public.changelog (
    store text NOT NULL,
    object_type text NOT NULL,
    object_id text NOT NULL,
    relation text NOT NULL,
    _user text NOT NULL,
    operation integer NOT NULL,
    ulid text NOT NULL,
    inserted_at timestamp with time zone NOT NULL,
    condition_name text,
    condition_context bytea
);


ALTER TABLE public.changelog OWNER TO delvauxo;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: delvauxo
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO delvauxo;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: delvauxo
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store; Type: TABLE; Schema: public; Owner: delvauxo
--

CREATE TABLE public.store (
    id text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);


ALTER TABLE public.store OWNER TO delvauxo;

--
-- Name: tuple; Type: TABLE; Schema: public; Owner: delvauxo
--

CREATE TABLE public.tuple (
    store text NOT NULL,
    object_type text NOT NULL,
    object_id text NOT NULL,
    relation text NOT NULL,
    _user text NOT NULL,
    user_type text NOT NULL,
    ulid text NOT NULL,
    inserted_at timestamp with time zone NOT NULL,
    condition_name text,
    condition_context bytea
);


ALTER TABLE public.tuple OWNER TO delvauxo;

--
-- Data for Name: assertion; Type: TABLE DATA; Schema: public; Owner: delvauxo
--

COPY public.assertion (store, authorization_model_id, assertions) FROM stdin;
\.


--
-- Data for Name: authorization_model; Type: TABLE DATA; Schema: public; Owner: delvauxo
--

COPY public.authorization_model (store, authorization_model_id, type, type_definition, schema_version, serialized_protobuf) FROM stdin;
01JYHBHDMXPZPN1FXPK1WDG6M0	01JYHBHDR0GZ6SZPRM4CW0WS5A		\N	1.1	\\x0a1a30314a59484248445230475a36535a50524d34435730575335411203312e311a060a04757365721a8d010a0964617368626f617264120b0a0561646d696e12020a00121a0a056f776e65721211220f0a020a000a091207120561646d696e121b0a0672656e7465721211220f0a020a000a091207120561646d696e1a3a0a120a0672656e74657212080a060a04757365720a110a0561646d696e12080a060a04757365720a110a056f776e657212080a060a0475736572
\.


--
-- Data for Name: changelog; Type: TABLE DATA; Schema: public; Owner: delvauxo
--

COPY public.changelog (store, object_type, object_id, relation, _user, operation, ulid, inserted_at, condition_name, condition_context) FROM stdin;
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	admin	admin	user:e4d137a8-ca21-4bd5-80dc-69cee3432bdb	0	01JZ34TB4VS8RJ7G6HEH7NCKBM	2025-07-01 14:03:55.931766+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	owner	admin	user:e4d137a8-ca21-4bd5-80dc-69cee3432bdb	0	01JZ34V66RXZK5FNNZYPEK9Q49	2025-07-01 14:04:23.640902+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	renter	admin	user:e4d137a8-ca21-4bd5-80dc-69cee3432bdb	0	01JZ34VMH0SV07HFT4Z0JRTWYY	2025-07-01 14:04:38.304671+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	renter	renter	user:15d36145-5cea-49e5-9f9f-fe71bfe502fb	0	01JZ34W20GM7XJ74H8CJNENB1J	2025-07-01 14:04:52.113298+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	owner	owner	user:ecacf8de-e81a-4ca7-83d6-d7fc200bf9a4	0	01JZ34WJ6K9EA6BY38PNJJ36R6	2025-07-01 14:05:08.692078+00		\N
\.


--
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: delvauxo
--

COPY public.goose_db_version (id, version_id, is_applied, tstamp) FROM stdin;
1	0	t	2025-07-01 14:02:22.539969
2	1	t	2025-07-01 14:02:22.564803
3	2	t	2025-07-01 14:02:22.585
4	3	t	2025-07-01 14:02:22.592313
5	4	t	2025-07-01 14:02:22.602779
6	5	t	2025-07-01 14:02:22.61063
\.


--
-- Data for Name: store; Type: TABLE DATA; Schema: public; Owner: delvauxo
--

COPY public.store (id, name, created_at, updated_at, deleted_at) FROM stdin;
01JYHBHDMXPZPN1FXPK1WDG6M0	parkigo-store	2025-06-24 16:15:03.837886+00	2025-06-24 16:15:03.837886+00	\N
\.


--
-- Data for Name: tuple; Type: TABLE DATA; Schema: public; Owner: delvauxo
--

COPY public.tuple (store, object_type, object_id, relation, _user, user_type, ulid, inserted_at, condition_name, condition_context) FROM stdin;
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	admin	admin	user:e4d137a8-ca21-4bd5-80dc-69cee3432bdb	user	01JZ34TB4VS8RJ7G6HEH7NCKBM	2025-07-01 14:03:55.931766+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	owner	admin	user:e4d137a8-ca21-4bd5-80dc-69cee3432bdb	user	01JZ34V66RXZK5FNNZYPEK9Q49	2025-07-01 14:04:23.640902+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	renter	admin	user:e4d137a8-ca21-4bd5-80dc-69cee3432bdb	user	01JZ34VMH0SV07HFT4Z0JRTWYY	2025-07-01 14:04:38.304671+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	renter	renter	user:15d36145-5cea-49e5-9f9f-fe71bfe502fb	user	01JZ34W20GM7XJ74H8CJNENB1J	2025-07-01 14:04:52.113298+00		\N
01JYHBHDMXPZPN1FXPK1WDG6M0	dashboard	owner	owner	user:ecacf8de-e81a-4ca7-83d6-d7fc200bf9a4	user	01JZ34WJ6K9EA6BY38PNJJ36R6	2025-07-01 14:05:08.692078+00		\N
\.


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: delvauxo
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 6, true);


--
-- Name: assertion assertion_pkey; Type: CONSTRAINT; Schema: public; Owner: delvauxo
--

ALTER TABLE ONLY public.assertion
    ADD CONSTRAINT assertion_pkey PRIMARY KEY (store, authorization_model_id);


--
-- Name: authorization_model authorization_model_pkey; Type: CONSTRAINT; Schema: public; Owner: delvauxo
--

ALTER TABLE ONLY public.authorization_model
    ADD CONSTRAINT authorization_model_pkey PRIMARY KEY (store, authorization_model_id, type);


--
-- Name: changelog changelog_pkey; Type: CONSTRAINT; Schema: public; Owner: delvauxo
--

ALTER TABLE ONLY public.changelog
    ADD CONSTRAINT changelog_pkey PRIMARY KEY (store, ulid, object_type);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: delvauxo
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: store store_pkey; Type: CONSTRAINT; Schema: public; Owner: delvauxo
--

ALTER TABLE ONLY public.store
    ADD CONSTRAINT store_pkey PRIMARY KEY (id);


--
-- Name: tuple tuple_pkey; Type: CONSTRAINT; Schema: public; Owner: delvauxo
--

ALTER TABLE ONLY public.tuple
    ADD CONSTRAINT tuple_pkey PRIMARY KEY (store, object_type, object_id, relation, _user);


--
-- Name: idx_reverse_lookup_user; Type: INDEX; Schema: public; Owner: delvauxo
--

CREATE INDEX idx_reverse_lookup_user ON public.tuple USING btree (store, object_type, relation, _user);


--
-- Name: idx_tuple_partial_user; Type: INDEX; Schema: public; Owner: delvauxo
--

CREATE INDEX idx_tuple_partial_user ON public.tuple USING btree (store, object_type, object_id, relation, _user) WHERE (user_type = 'user'::text);


--
-- Name: idx_tuple_partial_userset; Type: INDEX; Schema: public; Owner: delvauxo
--

CREATE INDEX idx_tuple_partial_userset ON public.tuple USING btree (store, object_type, object_id, relation, _user) WHERE (user_type = 'userset'::text);


--
-- Name: idx_tuple_ulid; Type: INDEX; Schema: public; Owner: delvauxo
--

CREATE UNIQUE INDEX idx_tuple_ulid ON public.tuple USING btree (ulid);


--
-- PostgreSQL database dump complete
--

